//  © Copyright ACI Worldwide, Inc. 2018, 2025

#ifndef Header_h
#define Header_h

typedef NSString * OPPPaymentBrand NS_STRING_ENUM;
extern OPPPaymentBrand const OPPPaymentBrandAffirm;
extern OPPPaymentBrand const OPPPaymentBrandAfterpayPacific;
extern OPPPaymentBrand const OPPPaymentBrandAMEX;
extern OPPPaymentBrand const OPPPaymentBrandApplePay;
extern OPPPaymentBrand const OPPPaymentBrandApplePayTkn;
extern OPPPaymentBrand const OPPPaymentBrandBancontactLink;
extern OPPPaymentBrand const OPPPaymentBrandBlik;
extern OPPPaymentBrand const OPPPaymentBrandBOLETO;
extern OPPPaymentBrand const OPPPaymentBrandCarteBleue;
extern OPPPaymentBrand const OPPPaymentBrandCashAppPay;
extern OPPPaymentBrand const OPPPaymentBrandChinaUnionPay;
extern OPPPaymentBrand const OPPPaymentBrandClearPay;
extern OPPPaymentBrand const OPPPaymentBrandDankort;
extern OPPPaymentBrand const OPPPaymentBrandDinersClub;
extern OPPPaymentBrand const OPPPaymentBrandDirectDebitSEPA;
extern OPPPaymentBrand const OPPPaymentBrandDiscover;
extern OPPPaymentBrand const OPPPaymentBrandGiropay;
extern OPPPaymentBrand const OPPPaymentBrandGooglePay;
extern OPPPaymentBrand const OPPPaymentBrandIDEAL;
extern OPPPaymentBrand const OPPPaymentBrandIkanoOiFI;
extern OPPPaymentBrand const OPPPaymentBrandIkanoOiNO;
extern OPPPaymentBrand const OPPPaymentBrandIkanoOiSE;
extern OPPPaymentBrand const OPPPaymentBrandIkanoPrivateLabelVA;
extern OPPPaymentBrand const OPPPaymentBrandInicis;
extern OPPPaymentBrand const OPPPaymentBrandInstantPay;
extern OPPPaymentBrand const OPPPaymentBrandJCB;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaInstallments;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaInvoice;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaPaymentsBillPay;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaPaymentsOne;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaPaymentsPayLater;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaPaymentsPayNow;
extern OPPPaymentBrand const OPPPaymentBrandKlarnaPaymentsSliceIt;
extern OPPPaymentBrand const OPPPaymentBrandMada;
extern OPPPaymentBrand const OPPPaymentBrandMaestro;
extern OPPPaymentBrand const OPPPaymentBrandMasterCard;
extern OPPPaymentBrand const OPPPaymentBrandMasterDebit;
extern OPPPaymentBrand const OPPPaymentBrandMasterpass;
extern OPPPaymentBrand const OPPPaymentBrandMBWAY;
extern OPPPaymentBrand const OPPPaymentBrandMultibanco;
extern OPPPaymentBrand const OPPPaymentBrandOney;
extern OPPPaymentBrand const OPPPaymentBrandPaydirekt;
extern OPPPaymentBrand const OPPPaymentBrandPayPal;
extern OPPPaymentBrand const OPPPaymentBrandPaysafecard;
extern OPPPaymentBrand const OPPPaymentBrandPaytrail;
extern OPPPaymentBrand const OPPPaymentBrandPostFinanceKarteDirect;
extern OPPPaymentBrand const OPPPaymentBrandPrzelewy;
extern OPPPaymentBrand const OPPPaymentBrandRatenkauf;
extern OPPPaymentBrand const OPPPaymentBrandRatePay;
extern OPPPaymentBrand const OPPPaymentBrandSOFORTBanking;
extern OPPPaymentBrand const OPPPaymentBrandSTCPay;
extern OPPPaymentBrand const OPPPaymentBrandTrustly;
extern OPPPaymentBrand const OPPPaymentBrandUnionPay;
extern OPPPaymentBrand const OPPPaymentBrandUnionPayGeneric;
extern OPPPaymentBrand const OPPPaymentBrandUnionPaySMS;
extern OPPPaymentBrand const OPPPaymentBrandUnknown;
extern OPPPaymentBrand const OPPPaymentBrandVipps;
extern OPPPaymentBrand const OPPPaymentBrandVISA;
extern OPPPaymentBrand const OPPPaymentBrandVisaDebit;
extern OPPPaymentBrand const OPPPaymentBrandVisaElectron;
extern OPPPaymentBrand const OPPPaymentBrandVPay;
extern OPPPaymentBrand const OPPPaymentBrandYandex;
extern OPPPaymentBrand const OPPPaymentBrandYandexCheckout;
extern OPPPaymentBrand const OPPPaymentBrandGenericCard;
extern OPPPaymentBrand const OPPPaymentBrandAmazonPay;
extern OPPPaymentBrand const OPPPaymentBrandMobilePay;

#endif /* OPPPaymentBrand */
