// Card Account Brands
export type CardAccountBrands =
  | 'AFFIRM' // AFFIRM	async
  | 'AIRPLUS' // AIRPLUS sync
  | 'ALIA' // ALIA	sync
  | 'AMEX' // AMEX	sync
  | 'APPLEPAY' // APPLEPAY	sync
  | 'ARGENCARD' // ARGENCARD	sync
  | 'AXP' // AXP	sync
  | 'BCMC' // BCMC	async
  | 'CABAL' // CABAL	sync
  | 'CABALDEBIT' // CABALDEBIT	sync
  | 'CARNET' // CARNET	sync
  | 'CARTEBANCAIRE' // CARTEBANCAIRE	sync
  | 'CARTEBLEUE' // CARTEBLEUE	sync
  | 'CENCOSUD' // CENCOSUD	sync
  | 'DANKORT' // DANKORT	sync
  | 'DINERS' // DINERS	sync
  | 'DISCOVER' // DISCOVER	sync
  | 'ELO' // ELO	sync
  | 'FACILYPAY_3X' // FACILYPAY_3X	async
  | 'GOOGLEPAY' // GOOGLEPAY	sync
  | 'HEB_GIFT_CARD' // HEB_GIFT_CARD	sync
  | 'HIPERCARD' // HIPERCARD	sync
  | 'JCB' // JCB	sync
  | 'MADA' // MADA	sync
  | 'MAESTRO' // MAESTRO	sync
  | 'MASTER' // MASTER	sync
  | 'MASTERDEBIT' // MASTERDEBIT	sync
  | 'MEEZA' // MEEZA	async
  | 'NARANJA' // NARANJA	sync
  | 'NATIVA' // NATIVA	sync
  | 'SCHEELS' // SCHEELS	sync
  | 'SERVIRED' // SERVIRED	sync
  | 'SISTEMACLAVE' // SISTEMACLAVE	async
  | 'STAPLES' // STAPLES	sync
  | 'TARJETASHOPPING' // TARJETASHOPPING	sync
  | 'TCARD' // TCARD	sync
  | 'TCARDDEBIT' // TCARDDEBIT	sync
  | 'VISA' // VISA	sync
  | 'VISADEBIT' // VISADEBIT	sync
  | 'VISAELECTRON' // VISAELECTRON	sync
  | 'VPAY'; // VPAY	sync
